---
name: WWW-DoctypeGrabber
version: 0.003
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: grab doctypes from webpages
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  Class::Data::Accessor: 0.04001
  LWP::UserAgent: 2.036
  overload: 1.04
build_requires:
  Test::More: 0
provides:
  WWW::DoctypeGrabber:
    file: lib/WWW/DoctypeGrabber.pm
    version: 0.003
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
