---
name: WWW-DoctypeGrabber
version: 0.005
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: grab doctypes from webpages
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  Carp: 1.04
  Class::Data::Accessor: 0.04001
  LWP::UserAgent: 2.036
  overload: 1.04
configure_requires:
  Module::Build: 0.35
provides:
  WWW::DoctypeGrabber:
    file: lib/WWW/DoctypeGrabber.pm
    version: 0.005
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
